### ISSUE TITLE
New path to Sites.php

### ISSUE THREAD

**Issue by uberhacker** [rvtraveller/terminus-composer#1]
Hey @rvtraveller: Nice to see another Terminus plugin!  I just noticed with version 0.13.1, there is a new path to Sites.php.  So you will need to change:
<code>
use Terminus\Models\Collections\Sites;
</code>
to:
<code>
use Terminus\Collections\Sites;
</code>
If you upgrade to the latest version, you will understand what I mean.  I can add a PR if you would like.
Thanks

**Comment by rvtraveller** [comment]
Thanks @uberhacker!  I had downgraded myself back to 0.12.0 because of pantheon-systems/terminus#1173.  I've opened a PR for this but am going to hold on merging it until the SSH problems get resolved.

**Comment by uberhacker** [comment]
Yeah, I have a PR which addresses the `sites list` issue <a href="https://github.com/pantheon-systems/terminus/pull/1244">#1222</a>.  You would think their `thorough` testing would catch these kinds of things before a release. LoL

**Comment by rvtraveller** [comment]
Since it seems like Terminus 0.13.\* is now stable, I've updated the plugin and done `thorough` testing.
