### ISSUE TITLE
Missing description?

### ISSUE THREAD

**Issue by uberhacker** [rvtraveller/terminus-composer#3]
Hey @rvtraveller: I also noticed your project is missing a description.  <a href="https://github.com/uberhacker/tps">Terminus Plugin Search</a> uses this for discovery.  Maybe you could just add something like the following?  As long as it has the keywords `Terminus` and `Plugin` in the description, it will be considered a valid plugin.
<code>
Terminus Plugin to run Composer commands on Pantheon sites.
</code>
Thanks

**Comment by rvtraveller** [comment]
Updated, thanks!
